# In conclusion

## So, what was this all about?

This syllabus gave an introduction to applied econometrics. As such, it follows in structure closely the first chapters of introductory econometric textbooks such as @stock2003introduction. However, it is not only much more concise, it as well focuses on what I (and colleagues) find important. Thus, it is not that the focus is on learning formula's. Statistical software will know what to do. It focuses much more on thinking about underlying causal mechanism and on the interpretation of the findings. Moreover, writing my own syllabus also allows me to highlight what I find important in doing empirical research. And one of the most important elements I find is the close connection between a theoretical framework and empirical research. And note though that previous literature can as well provide a theoretical framework. 

Also be fully aware of the focus of applied econometrics. It is really about the **identification** of a **causal** effect and not about prediction. In fact, some of the tools in applied econometrics (such as the use of fixed effects) hamper prediction. But know that for good prediction you need to establish a good causal framework.

## And now what?

The course is named *applied* econometrics and I really would like to emphasize the appliedness of it. In the end you get intuition for this but only after doing this multiple times. And not only in this course, but also in other courses and for writing theses. Empirical work is becoming more and more important---not only in economics but also in the other social sciences. 

After finishing this course you should have a good understanding of the basics of applied econometrics. More advanced courses always go back go this and especially to the least squares assumptions as defined in @sec-lsa. All more advanced techniques are only used because one of these assumptions (typically the first one) are violated. Finally, understanding this also allows you to read and understand most empirical findings as displayed in empirical economic articles. 